#@data/values
#@overlay/match-child-defaults missing_ok=True
---
system_namespace: cf-system
workloads_namespace: cf-workloads
staging_namespace: cf-workloads-staging

cf_api_server:   #!<-- pod
  replicas: 42   #!<-- default replica value
  cf_api_server:  #!<-- container
    resources:
      requests:
        mem: 300Mi  #!<-- default mem value
        cpu: 500m  #!<-- default cpu value
      limits:
        mem: 1.2Gi
        cpu: 1000m
