#@data/values
---
#! Default values for cf-k8s-networking.
#! This is a YTT-formatted file.
systemNamespace: cf-system
workloadsNamespace: cf-workloads

routecontroller:
  image: gcr.io/cf-networking-images/cf-k8s-networking/routecontroller:contour

service:
  externalPort: 80
